# Generated by Django 4.2.1 on 2023-06-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclasses', '0002_class_recording_payment_lesson_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
    ]
