# Generated by Django 4.2.1 on 2023-06-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclasses', '0003_user_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mentor',
        ),
    ]
