# Generated by Django 4.2.1 on 2023-06-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclasses', '0004_remove_course_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
